{{- if .Values.env.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}
spec:
  externalSecretName: {{ $.Values.fullnameOverride }}
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ $.Values.namespace }}
  externalSecretSpec:
    secretStoreRef:
      name: gcpsecretmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: {{ $.Values.fullnameOverride }}
      creationPolicy: Owner
    data:
     {{- range .Values.envFrom }}
      - secretKey: "{{ .secretRef.name |  replace $.Values.fullnameOverride "" | replace "-" "_" | trimAll "_" | upper }}" #key name in the k8s secret
        remoteRef: 
          key: {{ .secretRef.name }} #name of gcp secret
    {{- end }}
{{- end }}
