{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}.paydestal.com"
      secretName: "{{ .Values.ingress.host }}.paydestal.com"
  rules:
    - host: "{{ .Values.ingress.host }}.paydestal.com"
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.fullnameOverride }}
                port:
                  number: 80
            pathType: Prefix
            path: "/"
{{- end }}